### ISSUE TITLE
Missing data file? 

### ISSUE THREAD

**Issue by paigeduffin** [VollmerLab/Genomic-Signatures-of-Disease-Resistance-in-Staghorn-Corals#1]
Hello! 

I hope you are well! I'm looking to pull specific information about the symbiont composition of this dataset, and I believe I may have found a file that is necessary but has not been made publicly available.  

Specifically, I'm searching for the file "fastq_screen_results_summary.csv" read in on line 12 of the R code "symbiodinium_contamination_v_resistance.R". 

I apologize in advance if this is a mistake on my end, but - among other efforts - I did a search of that sample name in the download file made available for reproducibility and it neither returned as a file itself with that name, nor as a line of code indicating that file is written into existence during another step of the process. 

Any help would be greatly appreciated! Thank you!

**Comment by jdselwyn** [comment]
Hi Paige,

Thanks for getting in touch. I hadn't noticed this script hadn't been adjusted to assume a freshly cloned repository. I've added `intermediate_files/fastq_screen_results_summary.csv` and `intermediate_files/preprocessed_metadata.csv` (usually created in the `R_Code/2 - preprocess_genetics.R` script) to the intermediate files folder and fixed the file paths in the R script `R_Code/symbiodinium_contamination_v_resistance.R` so it should be able to be run from a freshly cloned repository without having to run the preceding scripts or deal with the SNP calling process.

Jason
